version: 0.2

phases:
  install:
    commands:
      - echo Build started on `date`
      - echo Installing Hugo
      - cd ~
      - wget https://github.com/gohugoio/hugo/releases/download/v0.37.1/hugo_0.37.1_Linux-64bit.deb
      - dpkg -i hugo*.deb
      - hugo version
  build:
    commands:
      - echo BUILD phase commands
      - cd $CODEBUILD_SRC_DIR
      - pwd
      - hugo
      - aws s3 sync public/ s3://shyamramineni.com/ --region ap-south-1
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
