baseURL = "https://shyamramineni.com/"
languageCode = "en-us"
title = "Shyam Ramineni"
theme = "hyde"

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[params]
  layoutReverse = false
  description = "This is place where I share my thoughts and learnings"
